### ISSUE TITLE
Updated Goedecker potentials

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/PseudoLibrary#9]
@mkrack recently contributed an extended set of GTH potentials to DFTK (https://github.com/JuliaMolSim/DFTK.jl/pull/950). The new location where the CP2K GTH potentials are stored is https://github.com/cp2k/cp2k-data/tree/master/potentials/Goedecker/cp2k. We should mirror them here or integrate with that repo.

**Comment by mkrack** [comment]
I suggest just to mirror the relevant sub-folders of the [cp2k-data](https://github.com/cp2k/cp2k-data/tree/master/potentials/Goedecker/cp2k) repository in the case of the GTH (HGH) potentials to `JuliaMolSim/PseudoLibrary/pseudos/gth`. These folders are the feedstock for the CP2K database file [GTH_POTENTIALS](https://github.com/cp2k/cp2k-data/blob/master/potentials/Goedecker/cp2k/GTH_POTENTIALS) used by [CP2K](https://github.com/cp2k/cp2k/tree/master/data). A subset of these GTH pseudopotentials has recently been tested in the framework of an exhaustive [verification study](https://doi.org/10.1038/s42254-023-00655-3). I propose to keep the same naming conventions, i.e. to use `GTH` instead of `HGH`, to avoid confusion.
The DFTK parsing of path and file names for the pseudos appears to be case insensitive which makes `gth/pbe/al-q3` and `GTH/PBE/Al-q3` equivalent.

**Comment by mfherbst** [comment]
We will use a different naming convention now on master and drop HGH in favour of GTH
